### ISSUE TITLE
Unifiquemos estilos de código

### ISSUE THREAD

**Issue by ElenaMLopez** [Formula-UC3M/telemetria-documentacion#34]
Tus tabulaciones tienen 2 o 4 espacios?
camel case for ever...
guiones bajos o medios?
Ese BEM para el CSS? o que?
...
...
muchas dudas me invaden... 
¿Qué os parece?

**Comment by Sediug** [comment]
Las mías son de 4. Me resulta más legible. Pero a mí me da igual.

**Comment by baumannzone** [comment]
Para eso están los linters/formateadores, para que haya unas reglas y que nadie se las salte y todo el código parezca escrito por la misma persona.

El tema de las reglas css es mas complicado de llevar @ElenaMLopez

**Comment by baumannzone** [comment]
Yo como norma general sigo estas pautas:

- Javascript: Comillas simples - `console.log('Hola mundo')`
- Html CSS: Comillas dobles `<h1 class="nombre-clase">`
- Clases CSS: guiones y guiones bajos en vez de _camelCase_ - Ej: `nombre-clase__modificador`
- Tabs siempre de 2 espacios

**Comment by baumannzone** [comment]
Os recomiendo esto: http://editorconfig.org/

**Comment by ElenaMLopez** [comment]
me parece todo ok!
tabulaciones 4 y BEM en el CSS con guiones bajos ;)
bicos!

**Comment by bytelovers** [comment]
@UlisesGascon solo la inicial de los web components en mayúsculas

**Comment by ElenaMLopez** [comment]
UY! que veo caras tristes por ahí, no gustan las tabulaciones de 4? o que jajajajaja
Pues se dejan en dos!

**Comment by Sediug** [comment]
Por mi parte el back tiene un .eslintrc dónde está definido el tema.
