### ISSUE TITLE
¿Necesitamos una organziación en Github?

### ISSUE THREAD

**Issue by UlisesGascon** [Formula-UC3M/telemetria-documentacion#40]
### Problematica
- Tendremos al menos dos repositorios para el proyecto (Telemetría y Landing para `http://formulauc3m.com/`)
- Podríamos tener incluso mas elementos para poder hacer el desarrollo más segmentado `telemetria-arduino`, `temetria-back`, `telemetria-front`... en un futuro

### Cambios
- El cambio principal sería tener una organización más en github como `goblin` o `ginger`
- La migración del repo es directa con lo que no es necesario hacer cambios en ningun entrono. Github hace la redirección automáticamente.

### ¿Como votar?
- Reacciona a este issue con 👍 o 👎 para dejar tu voto
- Añade un comentario si lo ves necesario, dejando tu opinión

**Comment by bytelovers** [comment]
Voto por hacer separación de repos ya y unificación (linteo) de códigos para que no cante

**Comment by bytelovers** [comment]
He creado la organización, para que no la pillen :D

Se llama Formula-UC3M, @UlisesGascon cuando quieras vemos como traspasar las issues y demás

**Comment by bytelovers** [comment]
@UlisesGascon ya lo tienes!

**Comment by Sediug** [comment]
El backend ya está, a ver si acabo ya todo (tengo algún bug en el auth y tal) y hago PR. He limpiado el repo y añadido las funcionalidades que faltaban.
